name: Visual Regression Testing

on:
  pull_request:
    branches:
      - main
      - develop
    # Only run if CSS/JS/MD-related files changed.
    paths:
      - '.github/workflows/visual-regression.yml'
      - 'assets/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '**.stories.js'
      - 'tests/backstop/**'
      - '.storybook/**'
      - '**.scss'
      - '.nvmrc'
      - '**/package.json'
      - 'package-lock.json'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  visual-regression:
    name: Run VR Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event.pull_request.draft == false
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Cache Node - npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-cache-
      - name: npm install
        run: npm i
      - name: Run Backstopjs
        run: while npm run backstopjs -- --storybook-host=./dist/ ; do echo SUCCESS ; sleep 1 ; done
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: vrt-report
          path: |
            tests/backstop/html_report
            tests/backstop/reference
            tests/backstop/tests
